#!/bin/bash
# Tiny bash script to run very simple tests.
# https://github.com/RiskoZoSlovenska/sest

NAME='sest'
VERSION='0.8.2'

NL=$'\n'
RUNNER_PYTHON='python3'
RUNNER_C='gcc'
RUNNER_CPP='g++'
TESTS_FAILED_CODE=64
LONG_LINES=150 # How many lines is considered "long"
IN_OUT_FILES_SUFFIX="//"

cases_file='tests.txt'
aux_cases_file=
has_aux_cases_file=false
case_delim='==='
input_delim='---'
runner=
needs_compile=false
requested_case=
fail_fast=false
timeout=0
tee_dest=/dev/null
verbose=false
print_output=true
color='auto'


# Just like echo but only does something if verbose is true
function verboseecho() {
	if $verbose; then
		echo "$@"
		return
	fi
}

# Performs cleanup, prints closing messages and exits with an appropriate code.
# Takes one argument: the number of errors encountered.
function finish {
	local msg_color=$green
	local exit_code=0

	if [ "$1" != 0 ]; then
		msg_color=$red
		exit_code=$TESTS_FAILED_CODE
	fi
	echo "${msg_color}$1 failure(s)$normal"
	exit $exit_code
}

function count_lines {
	echo -n "$1" | wc -l
}

function repeat_message {
	local message=$1
	local printed=$2

	if [ "$(count_lines "$printed")" -ge $LONG_LINES ]; then
		echo "${blue}The above output looks long; repeating the initial message:$NL> $normal$message$blue <$normal"
	fi
}

function readfile {
	local -n content=$1

	content=$(cat "$2" && echo '.')
	content=${content%.} # https://unix.stackexchange.com/a/10804
}

# $1: name of output array variable
# $2: text
# $3: delimiter
function split_str {
	local -n out=$1; out=()
	local text=$2
	local delim=$3
	local string=$text$delim

	# https://linuxhint.com/bash_split_examples
	while [ "$string" ]; do
		out+=("${string%%"$delim"*}")
		string=${string#*"$delim"}
	done
}

function print_help_and_exit {
	cat <<- EOM
$NAME - Risko's minimal(?) testing utility for competitive(?) programming

Usage: $NAME [OPTIONS...] ARGS... [-- ARGS...]

Available options:
  -h, --help                         Show this help text
      --version                      Show version
  -r, --runner=RUNNER                Interpreter to run the tests with
  -f, --file=FILE                    Read tests from FILE instead of ./$cases_file
  -D, --case-delimiter=CASE_DELIM    Use CASE_DELIM instead of '$case_delim' for
                                       separating cases
  -d, --delimiter=DELIM              Use DELIM instead of '$input_delim' for separating
                                       input/output
  -c, --case=CASE_NUM                Run only one specific test case
  -F, --fast                         Exit immediately on the first test failure
  -t, --timeout=X                    Timeout each case after X seconds
  -R, --reveal                       Mirror program output to the terminal
  -v, --verbose                      Be more verbose
  -o, --overview                     Do not print actual or expected test output
      --color=WHEN                   WHEN is 'auto' (def), 'always' or 'never'

Default runners:             Their extensions:          What they are:
  py, python, python3          .py, .py3                  Python ($RUNNER_PYTHON)
  c                            .c                         C ($RUNNER_C)
  c++, cpp                     .cpp, .cc                  C++ ($RUNNER_CPP)

Reads tests from FILE; calls the RUNNER with the given ARGS and test input as
stdin; verifies outputs. Handles compilation if necessary. If no RUNNER is
specified, it is guessed from the extension of the first argument.

FILE should be a normal text file. Cases are separated from each other by
CASE_DELIM, and the input/output of each case is separated by DELIM. Newlines
following delimiters are ignored.

If FILE is in the form X//, then only a single test case is run with input from
X.in and expected output from X.out. Use this for massive inputs.

Exits with a special error code of $TESTS_FAILED_CODE if any tests fail.
EOM
	exit
}

function print_version_and_exit {
	echo $VERSION
	exit
}


# Parse arguments (https://stackoverflow.com/a/14203146)
if [ $# = 0 ]; then
	print_help_and_exit
fi

positional_args=()
option_parsing_disabled=false

for i in "$@"; do
	if $option_parsing_disabled; then
		positional_args+=("$i")
		continue
	fi

	case $i in
	-h|--help)
		print_help_and_exit
		;;
	--version)
		print_version_and_exit
		;;
	-r=*|--runner=*)
		runner="${i#*=}"
		case $runner in
			py|python|python3)
				runner=$RUNNER_PYTHON
				;;
			c)
				runner=$RUNNER_C
				needs_compile=true
				;;
			c++|cpp)
				runner=$RUNNER_CPP
				needs_compile=true
				;;
			*)
				runner="${i#*=}"
				;;
		esac
		;;
	-f=*|--file=*)
		cases_file="${i#*=}"

		base="${cases_file%"$IN_OUT_FILES_SUFFIX"}"
		if [ "$cases_file" != "$base" ]; then
			cases_file="$base.in"
			aux_cases_file="$base.out"
			has_aux_cases_file=true
		fi
		;;
	-D=*|--case-delimiter=*)
		case_delim="${i#*=}"
		;;
	-d=*|--delimiter=*)
		input_delim="${i#*=}"
		;;
	-c=*|--case=*)
		requested_case="${i#*=}"
		;;
	-F|--fast)
		fail_fast=true
		;;
	-t=*|--timeout=*)
		timeout="${i#*=}"
		;;
	-R|--reveal)
		tee_dest=/dev/tty
		;;
	-v|--verbose)
		verbose=true
		;;
	-o|--overview)
		print_output=false
		;;
	--color=*)
	    color="${i#*=}"
		;;
	--)
		option_parsing_disabled=true
		;;
	--* | -*)
		echo >&2 "$NAME: unknown option '$i'"
		exit 1
		;;
	*)
		positional_args+=("$i")
		;;
	esac
done

set -- "${positional_args[@]}" # Restore positional parameters


# Set up colors (https://unix.stackexchange.com/a/10065)
# If colors are not requested, the color variables will be empty strings and
# we can still print them safely.
if [ "$color" = always ] || { [ "$color" = auto ] && [ -t 1 ]; }; then
    num_of_colors=$(tput colors)

    if [ "$num_of_colors" ] && [ "$num_of_colors" -ge 8 ]; then # Check if colors are supported
        normal="$(tput sgr0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        blue="$(tput setaf 4)" # 6 is cyan which is lighter and may be more pleasing
	fi
fi

# Guess runner
if [ -z "$runner" ]; then
	# https://stackoverflow.com/a/965072
	base=$(basename -- "$1")
	namebody=${base#.} # Don't use leading period for checking if there are periods
	if [ "$namebody" != "${namebody/./}"  ]; then # Parse extension only if there is one
		ext="${base##*.}"
	fi

	case $ext in
		py|py3)
			runner=$RUNNER_PYTHON
			;;
		c)
			runner=$RUNNER_C
			needs_compile=true
			;;
		cpp|cc)
			runner=$RUNNER_CPP
			needs_compile=true
			;;
	esac
fi

# Verify runner
if [ -z "$runner" ]; then
	echo >&2 "$NAME: no runner was provided and it couldn't be guessed from args; provide one manually"
	exit 1
elif ! [ -x "$runner" ] && ! command -v "$runner" &>/dev/null; then
	echo >&2 "$NAME: cannot use runner '$runner' since it is neither an executable file nor a command"
	exit 1
fi

if [ -x "$runner" ]; then
	runner="./$runner"
fi


# Make sure case files exist
if ! [ -r "$cases_file" ]; then
	echo >&2 "$NAME: '$cases_file' is not a readable file"
	exit 1
elif $has_aux_cases_file && ! [ -r "$aux_cases_file" ]; then
	echo >&2 "$NAME: '$aux_cases_file' is not a readable file"
	exit 1
fi


# Print configuration
in_out_files_name="'$cases_file'"
if $has_aux_cases_file; then
	in_out_files_name="$in_out_files_name and '$aux_cases_file'"
fi
echo "${blue}'$runner' against $in_out_files_name:$normal"


# Compile
if $needs_compile; then
	compiled_out=$(mktemp)
	verboseecho "${blue}Compiling to $compiled_out...$normal"

	if ! compile_msg=$($runner -o "$compiled_out" -O2 -Wall -Wextra "$@" 2>&1); then
		echo "${red}Compilation error!$normal"
		echo "$compile_msg"
		finish 1
	else
		verboseecho "$compile_msg"
		runner=$compiled_out
		trap '{
			verboseecho "${blue}Removing $compiled_out...$normal"
			rm "$compiled_out"
		}' EXIT
		set -- # Remove all command-line options since we consumed them already
	fi
fi


# Read + split input file
declare cases
verboseecho "${blue}Reading test cases...$normal"
if ! $has_aux_cases_file; then
	declare raw
	readfile raw "$cases_file"

	split_str cases "$raw" "$case_delim$NL"
else
	declare single_case_input single_case_output
	readfile single_case_input "$cases_file"
	readfile single_case_output "$aux_cases_file"

	cases+=("$single_case_input")
fi

# Run tests
case_num=0
failures_num=0
next_line_num=1
for case in "${cases[@]}"; do
	((case_num++))

	# Calculate line number
	cur_line_num=$next_line_num
	((next_line_num += $(count_lines "$case") + 1))

	# Check for a requested case
	if [ "$requested_case" ] && [ "$case_num" != "$requested_case" ]; then
		continue
	fi

	# Split case
	declare parts
	if ! $has_aux_cases_file; then
		split_str parts "$case" "$input_delim$NL"
	else
		parts=("$case" "$single_case_output")
	fi

	# Check case is formatted correctly
	num_parts=${#parts[@]}
	if [ "$num_parts" != 2 ]; then
		echo >&2 "$NAME: case $case_num is split up into $num_parts section(s), but exactly 2 are expected"
		exit 1
	fi

	input=${parts[0]}
	expected=${parts[1]}
	verboseecho "${blue}Running test case $case_num (line $cur_line_num)...$normal"

	# Run
	time_start=$(date '+%s.%N')

	actual="$(timeout --foreground "$timeout" "$runner" "$@" <<< "$input" 2>&1 | tee $tee_dest; echo ".${PIPESTATUS[0]}")"

	time_end=$(date '+%s.%N')
	run_time="$(bc -l <<< "scale=0; ($time_end - $time_start) * 1000 / 1")ms" # https://stackoverflow.com/a/13963375

	# Extract exit code from output
	runner_exit_code="$(grep -Eo '[0-9]+$' <<< "$actual" | tail -1)" # https://stackoverflow.com/a/44092231 and other replies
	actual="${actual%."$runner_exit_code"}"

	# Handle failure
	if [ "$runner_exit_code" != 0 ]; then
		err_desc="error"
		if [ "$runner_exit_code" = 124 ]; then
			err_desc="timed out"
		elif [ "$runner_exit_code" -gt 128 ]; then
			err_desc="$(kill -l $(("$runner_exit_code"-128)))"
		fi
		case $err_desc in
			SEGV) err_desc="segmentation fault" ;;
			FPE)  err_desc="floating point exception" ;;
			INT)  err_desc="interrupted" ;;
		esac

		message="${red}Case $case_num: Runtime error! ($run_time) (code $runner_exit_code: $err_desc)$normal"
		echo "$message"

		if $print_output; then
			printf "${blue}Output (%d):$normal\n%s\n" ${#actual} "$actual"
			repeat_message "$message" "$actual"
		fi

		((failures_num++))
		if $fail_fast; then finish $failures_num; else continue; fi
	fi

	# Check equality
	if [ "$actual" = "$expected" ]; then
		echo "${green}Case $case_num: OK ($run_time)$normal"
	else
		message="${red}Case $case_num: Wrong output! ($run_time)$normal"
		echo "$message"

		if $print_output; then
			printf "${blue}Expected (%d):$normal\n%s\n${blue}Got (%d):$normal\n%s\n" \
				${#expected} "$expected" ${#actual} "$actual"
			repeat_message "$message" "$expected$NL$actual"
		fi

		((failures_num++))
		if $fail_fast; then finish $failures_num; else continue; fi
	fi
done

finish $failures_num
